### ISSUE TITLE
Vertically aligning H gates

### ISSUE THREAD

**Issue by eshaspark** [qpic/qpic#8]
Hello,
My code has 3 Hadamard gates on different wires. Usually these are vertically aligned in a diagram, but my code gives the following output:
<img width="446" alt="Screenshot 2020-05-27 at 11 15 13 AM" src="https://user-images.githubusercontent.com/8880428/83038856-71a5d800-a00b-11ea-8126-1deba6bad2ac.png">

The code itself is this -
 W |\psi\rangle
b W |0\rangle
c W |0\rangle
a +b
a +c
a H
b H
c H
a b c G \rotatebox{90}{noise}
a H
b H
c H
a +c
a +b
+a b c

Could you let me know how to ensure the Hadamard gates are vertically aligned?

**Comment by KyleHutchings** [comment]
The reason this is occuring is because qpic places the gate at its earliest possible chance, because your second CNOT gate doesn't act on the second qubit it can perform the Hadamard at the same time. In order to fix it there are two possible options that come to mind: either use the TOUCH command on the second qubit after your CNOT to trick the compiler into thinking it was operated on, or specify that you want all the Hadamards to happen at the same time using LB and LE.
```
W |\psi\rangle
b W |0\rangle
c W |0\rangle
a +b
a +c
b TOUCH
a H
b H
c H
a b c G \rotatebox{90}{noise}
a H
b H
c H
a +c
a +b
+a b c
```

Or

```
W |\psi\rangle
b W |0\rangle
c W |0\rangle
a +b
a +c
LB
a H
b H
c H
LE
a b c G \rotatebox{90}{noise}
a H
b H
c H
a +c
a +b
+a b c
```

**Comment by eshaspark** [comment]
This works perfectly, thanks for the prompt workaround
